version: "3.7"
services: 
  qubeconvert-backend: 
    container_name: qubeconvert-backend
    build: ./backend/
    ports:
      - 8000:8000
    restart: unless-stopped
    networks:
      - qubeconvert
  qubeconvert-frontend: 
    container_name: qubeconvert-frontend
    build: ./frontend/
    ports:
      - 3000:80
    restart: unless-stopped
    networks:
      - qubeconvert

networks:
  qubeconvert:
    external: false
    name: qubeconvert
